DEVICE_PATH := device/oppo/A37m

ALLOW_MISSING_DEPENDENCIES := true

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true

TARGET_OTA_ASSERT_DEVICE := A37m

TARGET_USERIMAGES_USE_EXT4 := true

BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 elevator=deadline
TARGET_PREBUILT_KERNEL := device/oppo/A37m/prebuilt/Image.gz
BOARD_KERNEL_BASE := 0x80200000

TARGET_BOARD_PLATFORM := mt6750

TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_INCLUDE_REPACKTOOLS := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
RECOVERY_SDCARD_ON_DATA := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_LOGCAT := true
TARGET_USES_LOGD :=true

TARGET_BOOTLOADER_BOARD_NAME := A37m
TARGET_NO_BOOTLOADER := false

BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_HAS_NO_SELECT_BUTTOM := true
BOARD_SUPPRESS_SECURE_ERASE := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBx_8888"

TARGET_RECOVERY_FSTAB := device/oppo/A37m/recovery.fstab
